### ISSUE TITLE
Support WebJobs version 3.0.0

### ISSUE THREAD

**Issue by jsgoupil** [JSkimming/serilog-extensions-webjobs#11]
The new version completely changed. There is no more JobHostConfiguration.

**Comment by JSkimming** [comment]
@jsgoupil Yes I had a quick look and things have changed quite a lot and this library will need quite a rework, and may be redundant now Web Jobs uses the Logging Extensions.

**Comment by Hawxy** [comment]
You might want to look at Serilog.Extensions.Hosting which supports the generic hosting model that WJ 3.0 uses.

**Comment by NVK15** [comment]
Any updates on this? Will there be a support for latest webjob version? Looks like serilog doesn't seem to work with latest version of azure webjobs(V3.0.3)

**Comment by Hawxy** [comment]
> Any updates on this? Will there be a support for latest webjob version? Looks like serilog doesn't seem to work with latest version of azure webjobs(V3.0.3)

My suggestion still stands, you should use [Serilog.Extensions.Hosting](https://github.com/serilog/serilog-extensions-hosting) which works fine with WJ v3.

**Comment by pmiossec** [comment]
I'm also interested to see this package updated to support the new webjob api

@Hawxy 
>My suggestion still stands, you should use Serilog.Extensions.Hosting which works fine with WJ v3.

I prefer to see that package to be updated to have a `Serilog.Ilogger` [injected in the entrypoint method](https://github.com/JSkimming/serilog-extensions-webjobs#inject-ilogger-into-webjob-functions) and also get [automatic log message property enrichment](https://github.com/JSkimming/serilog-extensions-webjobs#automatic-log-message-property-enrichment)

**Comment by sander1095** [comment]
Any updates on this? :) Considering that getting logging to work correctly with App Insights and WebJobs, I am hesitant to use this package (or the suggested one by @Hawxy ) until I know that all my logs will work correctly! :)


I'd love to be able to use Serilog in all my projects!

**Comment by JSkimming** [comment]
@sander1095, I'm the author, I use Serilog in all my projects, including WebJobs and Azure Functions, and I no longer use this package.

There are a few gaps in functionality (injecting ILogger as a function parameter), though I've never cared enough to want to spend time on the rewrite. In this instance, I use constructor injection instead.

The main problem this library originally solved no longer exists since WebJobs (and by extension Azure Functions) use the  Logging Extensions that are part of .NET Core.

So, I suggest you follow the advice from @Hawxy and hesitate no longer.

**Comment by remy90** [comment]
Does anyone have a working boilerplate Serilog.Extensions.Hosting example they could share? I've logged an issue here showing my attempt: https://github.com/serilog/serilog-extensions-hosting/issues/46

**Comment by JSkimming** [comment]
@remy90 for completeness, here's the minimum set-up I also posted on the linked ticket

As I [mentioned above](#issuecomment-772606006) ⬆️ Use constructor injection.

> "There are a few gaps in functionality (injecting ILogger as a function parameter), though I've never cared enough to want to spend time on the rewrite. In this instance, I use constructor injection instead."

```csharp
class Program
{
    static async Task Main(string[] args)
    {
        Log.Logger = new LoggerConfiguration()
            .MinimumLevel.Information()
            .WriteTo.Console()
            .CreateLogger();

        IHostBuilder builder = Host.CreateDefaultBuilder(args)
            .UseSerilog(Log.Logger)
            .ConfigureAppConfiguration(config =>
            {
                config.AddInMemoryCollection(new Dictionary<string, string>
                {
                    ["AzureWebJobsStorage"] = "UseDevelopmentStorage=true",
                });
            })
            .ConfigureServices(s =>
            {
                s.AddSingleton(Log.Logger);
            })
            .ConfigureWebJobs(b =>
            {
                b.AddAzureStorageCoreServices();
                b.AddAzureStorage();
                b.AddTimers();
            });

        IHost host = builder.Build();
        try { await host.RunAsync(); }
        catch (Exception ex) { Log.Fatal(ex.Message, ex); }
        finally { Log.CloseAndFlush(); }
    }
}

public class Functions
{
    readonly ILogger _logger;

    public Functions(ILogger logger) => _logger = logger.ForContext<Functions>();

    public void ProcessQueueMessage([QueueTrigger("queue")] string message)
    {
        _logger.Information(message); // Serilog ILogger
    }

    public void ProcessTimer([TimerTrigger("0 * * * * *", RunOnStartup = true)] TimerInfo myTimer)
    {
        _logger.Information(
            "C# Timer trigger function executed at: {Now:R}! IsPastDue={IsPastDue}.",
            DateTime.UtcNow,
            myTimer.IsPastDue);
    }
}
```

I use these packages

```xml
<PackageReference Include="Microsoft.Azure.WebJobs" Version="3.0.27" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="4.0.1" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="4.0.4" />
<PackageReference Include="Microsoft.Extensions.Hosting" Version="5.0.0" />
<PackageReference Include="Serilog.Extensions.Hosting" Version="4.1.2" />
<PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
```

**Comment by sander1095** [comment]
Does anyone know of any differences between  an ilogger from the function param vs the constructor?

**Comment by JSkimming** [comment]
As far as I know, nothing. The class is instantiated for every function invocation.
