### ISSUE TITLE
How to set minimum log level

### ISSUE THREAD

**Issue by jjacob114** [JSkimming/serilog-extensions-webjobs#2]
I tried to set the minimum log level to Verbose but nothing seems to be working. The logger always defaults to Information log level. Tried:

1) Setting MinimumLogLevel.Verbose() on the LoggerConfiguration
2) Passing TraceLevel.Verbose to UseSerilog()

How do you configure log level properly?

**Comment by JSkimming** [comment]
Hi @jjacob114 I've yet to try more than informational logging with WebJobs, from a cursory look what you describe should work. I'll have a quick test at some point and see what I find.

**Comment by jjacob114** [comment]
Thank you, James! I tried with another extension (that allows you to add Serilog to web jobs) and I wasn’t able to get that one to log out under Information either.

**Comment by JSkimming** [comment]
@jjacob114 I've certainly been able to get logging at Information level to show.

What other extension were you using out of interest?

**Comment by JSkimming** [comment]
@jjacob114 I've found the issue and I have a simple fix. Which version of this library are you using [0.2.0](https://www.nuget.org/packages/Serilog.Extensions.WebJobs/0.2.0) or [0.5.0](https://www.nuget.org/packages/Serilog.Extensions.WebJobs/0.5.0)?

**Comment by JSkimming** [comment]
@jjacob114 I've just released [v0.2.1](https://www.nuget.org/packages/Serilog.Extensions.WebJobs/0.2.1), built on top of 0.2.0.
