### ISSUE TITLE
Raise Mircosoft.Azure.Webjob to beta 3

### ISSUE THREAD

**Issue by swoosh32us** [JSkimming/serilog-extensions-webjobs#3]
i was wonder was there anything in your backlog  to raise this exenstion to the new version of the azure web jobs dll

**Comment by swoosh32us** [comment]
if not ill submit a pull request

**Comment by JSkimming** [comment]
Hey @swoosh32us, good idea. I've been waiting for web jobs to leave beta, but they're taking a while, and I agree it's worth updating to the current beta.

I'm not actively developing any web jobs at the moment, so I'm unlikely to try this _out in the wild_ in the near term, so your feedback would be welcome.

I try to give time to open source projects at the weekend, so you may have to wait a few days before I'm able to look into this.

**Comment by JSkimming** [comment]
Hi, @swoosh32us this has just been released as [v0.6.0 on NuGet](https://www.nuget.org/packages/Serilog.Extensions.WebJobs/0.6.0 "Serilog.Extensions.WebJobs 0.6.0").

**Comment by swoosh32us** [comment]
Thanks man this is awesome
