### ISSUE TITLE
MissingMethodException when calling UseSerilog

### ISSUE THREAD

**Issue by SethDG** [JSkimming/serilog-extensions-webjobs#8]
When I try and call UseSerilog on my instance of JobHostConfiguration, I'm getting this exception:

System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Microsoft.Azure.WebJobs.Host.JobHostTraceConfiguration Microsoft.Azure.WebJobs.JobHostConfiguration.get_Tracing()'.
  Source=Serilog.Extensions.WebJobs
  StackTrace:
   at Serilog.SerilogJobHostConfigurationExtensions.UseSerilog(JobHostConfiguration config, TraceLevel level)

**Comment by JSkimming** [comment]
@SethDG What version of WebJobs are you using, this looks like a version mismatch.

**Comment by SethDG** [comment]
@JSkimming 3.0.0-beta5

**Comment by JSkimming** [comment]
@SethDG It looks like there's a breaking change between beta4 and 5 on the WebJobs packages. I'm not sure what's required to fix it yet, but you can downgrade to bata4 to fix the issue.

**Comment by SethDG** [comment]
@JSkimming Thanks!
